config/routes.rb
FiercePunchClock::Application.routes.draw do
  devise_for :members
  get "welcome/index"

  root 'welcome#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :user, through: :user_employer
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many:user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :member
  has_many :employer, through: :user_employer
end

app/models/user_employer.rb
class UserEmployer < ActiveRecord::Base
  belongs_to :user
  belongs_to :employer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #magical thing that forces login on every page
  before_action :authenticate_member!
  
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_member_widget.html.erb
<!-- Calls magical devise method to see if someone is signed in and gives appropriate links -->
<div class="devise">
	<small>
		<% if member_signed_in? %>
			<%= current_member.email %>, 
			<%= link_to 'Logout', destroy_member_session_path, :method => :delete %>
		<% else %>
			You are not signed in. 
			<%= link_to 'Login', new_member_session_path %>
		<% end %>
	</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FiercePunchClock</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="page">
		<header>
			<%= image_tag("fiercepunchicon_128.png", :size => '32') %>
			<h1>Fierce Punch Clock</h1>
			<%= render 'layouts/member_widget' %>
		</header>
		<main>
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		
			<%= yield %>
		</main>
		<footer>
			<small>Fierce Punch Studios 2014.</small>
		</footer>
	</div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, World!</h1>
<p>Have some p. Community P.</p>